#!/usr/bin/env node
const { execSync } = require("child_process");
const { resolve } = require("path");
const esbuild = require("esbuild");

try {
  const { copyDir, outputDirectory, options } = JSON.parse(process.argv[2]);

  if (copyDir) {
    console.log(`Copy additional files from '${copyDir}'`);
    const srcDir = resolve(copyDir) + '/.';
    const copyCommand = `cp -r ${srcDir} ${outputDirectory}`;
    console.log(copyCommand);
    execSync(copyCommand)
  }

  console.log("Bundling with the following options...", options);
  esbuild.buildSync(options);
} catch (error) {
  console.error(error.message);
  process.exit(1);
}
