#!/usr/bin/env node
const esbuild = require("esbuild");

try {
  const options = JSON.parse(process.argv[2]);
  console.log("Bundling with the following options...", options);
  esbuild.buildSync(options);
} catch (error) {
  console.error(error.message);
  process.exit(1);
}
